<a href="https://colab.research.google.com/github/adsoftsito/tensorflow-iot/blob/main/model_regresionlineal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
try:
    %tensorflow_version 2.x
except:
    pass

In [2]:
# Helper libraries
import numpy as np
import os
 
# TensorFlow
import tensorflow as tf
 
print(tf.__version__)

2.4.1


In [3]:
X = np.arange(-10.0, 10.0, 1e-2)
np.random.shuffle(X)
y = 2 * X + 1
print(X)
print(y) 
train_end = int(0.6 * len(X))
test_start = int(0.8 * len(X))
print(train_end)
print(test_start) 
X_train, y_train = X[:train_end], y[:train_end]
print(X_train)
print(y_train)
X_test, y_test = X[test_start:], y[test_start:]
X_val, y_val = X[train_end:test_start], y[train_end:test_start]

[-4.19  4.63 -9.07 ... -5.89 -9.67 -7.64]
[ -7.38  10.26 -17.14 ... -10.78 -18.34 -14.28]
1200
1600
[-4.19  4.63 -9.07 ... -5.67 -4.28  3.77]
[ -7.38  10.26 -17.14 ... -10.34  -7.56   8.54]


In [4]:
tf.keras.backend.clear_session()
linear_model = tf.keras.models.Sequential([
                                           tf.keras.layers.Dense(units=1, input_shape=[1], name='Single')
                                           ])
linear_model.compile(optimizer=tf.keras.optimizers.SGD(), loss=tf.keras.losses.mean_squared_error)
linear_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
Single (Dense)               (None, 1)                 2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [5]:
linear_model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=20)
print(linear_model.evaluate(X_test, y_test, verbose=0))
print(round(linear_model.predict([7.443]).tolist()[0][0], 4))    # expected: 15.886

Epoch 1/20
38/38 [==============================] - 1s 12ms/step - loss: 2.2864 - val_loss: 0.2286
Epoch 2/20
38/38 [==============================] - 0s 2ms/step - loss: 0.1566 - val_loss: 0.0489
Epoch 3/20
38/38 [==============================] - 0s 2ms/step - loss: 0.0331 - val_loss: 0.0099
Epoch 4/20
38/38 [==============================] - 0s 2ms/step - loss: 0.0071 - val_loss: 0.0021
Epoch 5/20
38/38 [==============================] - 0s 2ms/step - loss: 0.0015 - val_loss: 4.6841e-04
Epoch 6/20
38/38 [==============================] - 0s 2ms/step - loss: 3.4194e-04 - val_loss: 9.9867e-05
Epoch 7/20
38/38 [==============================] - 0s 2ms/step - loss: 7.2217e-05 - val_loss: 2.3901e-05
Epoch 8/20
38/38 [==============================] - 0s 2ms/step - loss: 1.5697e-05 - val_loss: 4.6543e-06
Epoch 9/20
38/38 [==============================] - 0s 2ms/step - loss: 3.4225e-06 - val_loss: 9.8111e-07
Epoch 10/20
38/38 [==============================] - 0s 2ms/step - loss: 7.1091e-

In [6]:
export_path = 'linear_model/1/'
tf.saved_model.save(linear_model, os.path.join('/content/',export_path))

from google.colab import files
download_path = '/content/my_linear_model.zip'
!zip -r {download_path} {export_path}
files.download(download_path)

INFO:tensorflow:Assets written to: /content/linear_model/1/assets
  adding: linear_model/1/ (stored 0%)
  adding: linear_model/1/variables/ (stored 0%)
  adding: linear_model/1/variables/variables.index (deflated 44%)
  adding: linear_model/1/variables/variables.data-00000-of-00001 (deflated 63%)
  adding: linear_model/1/saved_model.pb (deflated 85%)
  adding: linear_model/1/assets/ (stored 0%)


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>